/**
 * @typedef {string} EventEnum
 * @property {string} UNBOUND_ERROR
 * @property {string} HOME_SUBSCRIPTION_CARD_SUBSCRIBE_CLICK
 * @property {string} FETCH_USER_BY_EMAIL_SUCCESS
 * @property {string} FETCH_USER_BY_EMAIL_ERROR
 * @property {string} SUBMIT_SUBSCRIPTION
 * @property {string} POST_SUBSCRIPTION_SUCCESS
 * @property {string} POST_SUBSCRIPTION_ERROR
 * @property {string} SUBMIT_EMAIL
 */

/**
 * @enum {EventEnum}
 */
const EventEnum = Object.freeze({
  UNBOUND_ERROR: 'UNBOUND_ERROR',
  CHANGE_THEME: 'CHANGE_THEME',
  CHANGE_LOCALE: 'CHANGE_LOCALE',
  HOME_SUBSCRIPTION_CARD_SUBSCRIBE_CLICK: 'HOME_SUBSCRIPTION_CARD_SUBSCRIBE_CLICK',
  HOME_EMAIL_FORM_SUCCESS: 'HOME_EMAIL_FORM_SUCCESS',
  HOME_EMAIL_FORM_ERROR: 'HOME_EMAIL_FORM_ERROR',
  SUBMIT_SUBSCRIPTION: 'SUBMIT_SUBSCRIPTION',
  POST_SUBSCRIPTION_SUCCESS: 'POST_SUBSCRIPTION_SUCCESS',
  POST_SUBSCRIPTION_ERROR: 'POST_SUBSCRIPTION_ERROR',
  SUBMIT_EMAIL: 'SUBMIT_EMAIL'
})

export default EventEnum
